### ISSUE TITLE
Using WIF to authenticate with on GHA doesn't allow for deployment of functions

### ISSUE THREAD

**Issue by sam-teleprompter-apps** [firebase/firebase-admin-node#2842]
I'm still having troubles using WIF, where as using a credentials files with google auth used to work. The auth step passes fine and produces a credentials file, but when attempting to deploy functions with the config file, I get the below error:

Error: Failed to authenticate, have you run firebase login?

Here is the workflow I'm using:

```
name: Deploy to Firebase Functions via github action
"on":
  push:
    branches:
      - sam/gha-testing
env:
  CI: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v4'

      - name: Download deps
        working-directory: functions
        run: |
            npm install
            npm install -g firebase-tools

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: '{redcated}'
          access_token_scopes: '{redcated}'
          workload_identity_provider: '{redacted}'
          service_account: '{redcated}'
          create_credentials_file: true
        
      - run: |
          echo "SERVICE_ACCOUNT_KEY=$(cat "${{ steps.auth.outputs.credentials_file_path }}" | tr -d '\n')" >> $GITHUB_ENV

      - name: Deploy
        run: npx firebase-tools deploy --only functions:functionsname
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
```

And the versions of the various Firebase products we're using:

```
    "firebase-admin": "^13.0.2",
    "firebase-tools": "13.18.0",
    "firebase-functions": "^6.3.1",
```

Just to reiterate, this was worked fine when supplying a credentials file to the Google Auth step.
